# Data load

In [1]:
from src.helpers import load_view

df_customers = load_view("vw_customer_summary_python")
df_monthly_sales = load_view("vw_monthly_sales_summary")
df_products = load_view("vw_products_summary")
df_delivery = load_view("vw_delivery_summary")
df_reviews = load_view("vw_order_review_summary")

# Data overview

In [2]:
from src.helpers import basic_overview

basic_overview(df_customers, "Customers Summary")

===Customers Summary===
(96096, 11)
                 customer_unique_id customer_city customer_state  \
0  0000366f3b9a7992bf8c76cfdf3221e2       cajamar             SP
1  0000b849f77a49e4a4ce2b2a4ca5be3f        osasco             SP
2  0000f46a3911fa3c0805444483337064      sao jose             SC
3  0000f6ccb0745a6a4b88665a16c9f078         belem             PA
4  0004aac84e0df4da2b147fca70cf8255      sorocaba             SP

  first_purchase_date first_purchase_month  last_purchase_date  \
0 2018-05-10 10:56:27           2018-05-01 2018-05-10 10:56:27
1 2018-05-07 11:11:27           2018-05-01 2018-05-07 11:11:27
2 2017-03-10 21:05:03           2017-03-01 2017-03-10 21:05:03
3 2017-10-12 20:29:41           2017-10-01 2017-10-12 20:29:41
4 2017-11-14 19:45:42           2017-11-01 2017-11-14 19:45:42

   customer_tenure_days  total_orders  failed_orders  total_spent  \
0                     0             1              0       141.90
1                     0             1              0        27.19
2                     0             1              0        86.22
3                     0             1              0        43.62
4                     0             1              0       196.89

   avg_order_value
0           141.90
1            27.19
2            86.22
3            43.62
4           196.89
<class 'pandas.DataFrame'>
RangeIndex: 96096 entries, 0 to 96095
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_unique_id    96096 non-null  str
 1   customer_city         96096 non-null  str
 2   customer_state        96096 non-null  str
 3   first_purchase_date   96096 non-null  datetime64[us]
 4   first_purchase_month  96096 non-null  datetime64[us]
 5   last_purchase_date    96096 non-null  datetime64[us]
 6   customer_tenure_days  96096 non-null  int64
 7   total_orders          96096 non-null  int64
 8   failed_orders         96096 non-null  int64
 9   total_spent           94989 non-null  float64
 10  avg_order_value       94989 non-null  float64
dtypes: datetime64[us](3), float64(2), int64(3), str(3)
memory usage: 8.1 MB
              first_purchase_date        first_purchase_month  \
count                       96096                       96096
mean   2017-12-30 19:19:10.429206  2017-12-15 15:48:05.214785
min           2016-09-04 21:15:19         2016-09-01 00:00:00
25%           2017-09-11 19:52:06         2017-09-01 00:00:00
50%           2018-01-18 13:33:08         2018-01-01 00:00:00
75%           2018-05-04 10:38:45         2018-05-01 00:00:00
max           2018-10-17 17:30:18         2018-10-01 00:00:00
std                           NaN                         NaN

               last_purchase_date  customer_tenure_days  total_orders  \
count                       96096          96096.000000  96096.000000
mean   2018-01-02 12:40:19.655865              2.722954      1.034809
min           2016-09-04 21:15:19              0.000000      1.000000
25%    2017-09-15 09:04:17.250000              0.000000      1.000000
50%           2018-01-21 19:39:16              0.000000      1.000000
75%    2018-05-06 20:14:49.750000              0.000000      1.000000
max           2018-10-17 17:30:18            633.000000     17.000000
std                           NaN             25.445278      0.214384

       failed_orders   total_spent  avg_order_value
count   96096.000000  94989.000000     94989.000000
mean        0.012841    165.694312       160.752791
min         0.000000      9.590000         9.590000
25%         0.000000     63.100000        62.440000
50%         0.000000    107.900000       105.740000
75%         0.000000    182.940000       176.990000
max         3.000000  13664.080000     13664.080000
std         0.113968    226.740844       219.897719

In [3]:
basic_overview(df_monthly_sales, "Monthly Sales Summary")

===Monthly Sales Summary===
(25, 10)
  purchase_month  total_orders  total_customers  total_revenue  \
0     2016-09-01             4                4         252.24
1     2016-10-01           324              321       59090.48
2     2016-12-01             1                1          19.62
3     2017-01-01           800              765      138488.04
4     2017-02-01          1780             1755      291908.01

   avg_order_value  avg_orders_per_customer  cancelled_orders  \
0            84.08                        1                 2
1           182.38                        1                24
2            19.62                        1                 0
3           173.11                        1                 3
4           163.99                        1                17

   cancellation_rate  unavailable_orders  unavailable_rate
0              50.00                   0              0.00
1               7.41                   7              2.16
2               0.00                   0              0.00
3               0.38                  10              1.25
4               0.96                  45              2.53
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   purchase_month           25 non-null     datetime64[us]
 1   total_orders             25 non-null     int64
 2   total_customers          25 non-null     int64
 3   total_revenue            25 non-null     float64
 4   avg_order_value          25 non-null     float64
 5   avg_orders_per_customer  25 non-null     int64
 6   cancelled_orders         25 non-null     int64
 7   cancellation_rate        25 non-null     float64
 8   unavailable_orders       25 non-null     int64
 9   unavailable_rate         25 non-null     float64
dtypes: datetime64[us](1), float64(4), int64(5)
memory usage: 2.1 KB
            purchase_month  total_orders  total_customers  total_revenue  \
count                   25     25.000000        25.000000   2.500000e+01
mean   2017-09-28 12:28:48   3977.640000      3921.840000   6.403549e+05
min    2016-09-01 00:00:00      1.000000         1.000000   1.962000e+01
25%    2017-04-01 00:00:00   1780.000000      1755.000000   2.919080e+05
50%    2017-10-01 00:00:00   4285.000000      4212.000000   6.743963e+05
75%    2018-04-01 00:00:00   6512.000000      6460.000000   1.023880e+06
max    2018-10-01 00:00:00   7544.000000      7430.000000   1.194883e+06
std                    NaN   2699.938516      2668.276702   4.316790e+05

       avg_order_value  avg_orders_per_customer  cancelled_orders  \
count         25.00000                     25.0         25.000000
mean         158.04520                      1.0         25.000000
min           19.62000                      1.0          0.000000
25%          154.84000                      1.0         15.000000
50%          160.82000                      1.0         24.000000
75%          168.36000                      1.0         29.000000
max          277.47000                      1.0         84.000000
std           41.38646                      0.0         19.478621

       cancellation_rate  unavailable_orders  unavailable_rate
count          25.000000           25.000000         25.000000
mean           10.540000           24.360000          0.688400
min             0.000000            0.000000          0.000000
25%             0.380000            7.000000          0.110000
50%             0.620000           18.000000          0.660000
75%             1.090000           38.000000          1.110000
max           100.000000           84.000000          2.530000
std            27.821032           21.889647          0.670421

In [4]:
basic_overview(df_products, "Products Summary")

===Products Summary===
(74, 7)
        product_category_name  total_orders  products_sold  total_revenue  \
0  agro_industry_and_commerce           182            212       72530.47
1            air_conditioning           251            295       54723.16
2                         art           201            208       24167.64
3       arts_and_craftmanship            23             24        1814.01
4                       audio           349            363       50668.60

   avg_product_price  total_freight  avg_freight
0             342.12        5843.60        27.56
1             185.50        6713.41        22.76
2             116.19        4028.57        19.37
3              75.58         370.13        15.42
4             139.58        5702.66        15.71
<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_category_name  74 non-null     str
 1   total_orders           74 non-null     int64
 2   products_sold          74 non-null     int64
 3   total_revenue          74 non-null     float64
 4   avg_product_price      74 non-null     float64
 5   total_freight          74 non-null     float64
 6   avg_freight            74 non-null     float64
dtypes: float64(4), int64(2), str(1)
memory usage: 4.2 KB
       total_orders  products_sold  total_revenue  avg_product_price  \
count     74.000000      74.000000   7.400000e+01          74.000000
mean    1337.864865    1515.175676   1.824276e+05         145.918243
std     2227.406935    2553.799814   2.971607e+05         145.328745
min        2.000000       2.000000   2.832900e+02          25.340000
25%       76.000000      77.750000   8.097403e+03          78.510000
50%      244.500000     277.500000   4.584633e+04         114.505000
75%     1395.750000    1664.750000   1.878776e+05         152.812500
max     9399.000000   11097.000000   1.255695e+06        1098.340000

       total_freight  avg_freight
count      74.000000    74.000000
mean    30291.133243    21.580676
std     49293.886028     8.136103
min        41.220000    11.940000
25%      1701.892500    16.287500
50%      6610.615000    19.265000
75%     31082.185000    22.657500
max    204422.070000    48.450000

In [5]:
basic_overview(df_delivery, "Delivery Summary")

===Delivery Summary===
(23, 10)
  order_month  completed_orders  avg_delivery_days  median_delivery_days  \
0  2016-09-01                 1               55.0                  55.0
1  2016-10-01               265               20.0                  18.0
2  2016-12-01                 1                5.0                   5.0
3  2017-01-01               750               13.0                  11.0
4  2017-02-01              1653               13.0                  11.0

   avg_processing_days  avg_shipping_days  on_time_orders  late_orders  \
0                  0.0                2.0               0            1
1                  1.0                6.0             263            2
2                  0.0                1.0               1            0
3                  1.0                9.0             728           22
4                  0.0               10.0            1604           49

   on_time_rate  avg_estimation_error
0          0.00                  36.0
1         99.25                 -37.0
2        100.00                 -22.0
3         97.07                 -27.0
4         97.04                 -19.0
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_month           23 non-null     datetime64[us]
 1   completed_orders      23 non-null     int64
 2   avg_delivery_days     23 non-null     float64
 3   median_delivery_days  23 non-null     float64
 4   avg_processing_days   23 non-null     float64
 5   avg_shipping_days     23 non-null     float64
 6   on_time_orders        23 non-null     int64
 7   late_orders           23 non-null     int64
 8   on_time_rate          23 non-null     float64
 9   avg_estimation_error  23 non-null     float64
dtypes: datetime64[us](1), float64(6), int64(3)
memory usage: 1.9 KB
                      order_month  completed_orders  avg_delivery_days  \
count                          23         23.000000          23.000000
mean   2017-08-28 20:52:10.434782       4194.695652          14.260870
min           2016-09-01 00:00:00          1.000000           5.000000
25%           2017-03-16 12:00:00       2424.500000          11.000000
50%           2017-09-01 00:00:00       4193.000000          12.000000
75%           2018-02-15 00:00:00       6453.000000          15.000000
max           2018-08-01 00:00:00       7289.000000          55.000000
std                           NaN       2481.181398           9.435029

       median_delivery_days  avg_processing_days  avg_shipping_days  \
count             23.000000            23.000000          23.000000
mean              12.565217             0.478261           8.434783
min                5.000000             0.000000           1.000000
25%                9.500000             0.000000           7.500000
50%               10.000000             0.000000           9.000000
75%               13.000000             1.000000          10.000000
max               55.000000             1.000000          13.000000
std                9.642831             0.510754           3.012490

       on_time_orders  late_orders  on_time_rate  avg_estimation_error
count       23.000000    23.000000     23.000000             23.000000
mean      3910.260870   284.086957     90.493913            -12.130435
min          0.000000     0.000000      0.000000            -37.000000
25%       2291.000000    83.000000     93.440000            -13.000000
50%       4071.000000   151.000000     95.610000            -13.000000
75%       5953.000000   398.000000     97.055000            -11.000000
max       6666.000000  1328.000000    100.000000             36.000000
std       2258.348053   341.125798     20.215867             12.512918

In [6]:
basic_overview(df_reviews, "Order Reviews Summary")

===Order Reviews Summary===
(99224, 11)
                          review_id                          order_id  \
0  cb6fe4f91f83d9222b7c8e14959055e1  84226f5c73669d7711ca44aa9cac602a
1  45a523faa4defdf60118a90301b8a23e  26c4ac9998f72d4fcdca3c6e27089f1b
2  6eab2c9b7ea4975a0b0357a4c464b356  55101b36a58251926b6cbfdb540c0461
3  500c05500aa275953129f49799ee5c73  8a9424899aac432d80d8e580932b5ee9
4  399133d47ddc5f40df57c1ceba4e4540  603d76b730c972775ccf2a910bf23490

                 customer_unique_id  review_score review_sentiment  \
0  3894553e805e7701befe17655de23870             3          Neutral
1  f4af0c607eaeb3bc3f5b9eddad049396             3          Neutral
2  35a412904ddbb1be0734bfe8dc2c6796             4         Positive
3  7bf8aae1f297a6cf8573f9da5286435d             5         Positive
4  38c21a5932d9a1298ed51f53bf6c7f91             5         Positive

  order_status  successful_order purchase_month  delivery_days  \
0    delivered              True     2018-04-01            9.0
1    delivered              True     2017-10-01           22.0
2    delivered              True     2018-05-01           17.0
3    delivered              True     2018-07-01           13.0
4    delivered              True     2018-03-01            7.0

   delivery_delay_days is_late_delivery
0                -14.0            False
1                -12.0            False
2                  0.0            False
3                -13.0            False
4                -16.0            False
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   review_id            99224 non-null  str
 1   order_id             99224 non-null  str
 2   customer_unique_id   99224 non-null  str
 3   review_score         99224 non-null  int64
 4   review_sentiment     99224 non-null  str
 5   order_status         99224 non-null  str
 6   successful_order     99224 non-null  bool
 7   purchase_month       99224 non-null  datetime64[us]
 8   delivery_days        96359 non-null  float64
 9   delivery_delay_days  96359 non-null  float64
 10  is_late_delivery     96359 non-null  object
dtypes: bool(1), datetime64[us](1), float64(2), int64(1), object(1), str(5)
memory usage: 7.7+ MB
       review_score              purchase_month  delivery_days  \
count  99224.000000                       99224   96359.000000
mean       4.086421  2017-12-16 01:17:22.876723      12.461991
min        1.000000         2016-09-01 00:00:00       0.000000
25%        4.000000         2017-09-01 00:00:00       7.000000
50%        5.000000         2018-01-01 00:00:00      10.000000
75%        5.000000         2018-05-01 00:00:00      16.000000
max        5.000000         2018-10-01 00:00:00     208.000000
std        1.347579                         NaN       9.466713

       delivery_delay_days
count         96359.000000
mean            -11.917797
min            -147.000000
25%             -17.000000
50%             -12.000000
75%              -7.000000
max             188.000000
std              10.114024

Customers Summary: We are anticipating null values in df_customers based on the logic applied (total_spent was calculated only for succesfull orders)

In [7]:
df_customers.isnull().sum()

customer_unique_id         0
customer_city              0
customer_state             0
first_purchase_date        0
first_purchase_month       0
last_purchase_date         0
customer_tenure_days       0
total_orders               0
failed_orders              0
total_spent             1107
avg_order_value         1107
dtype: int64

Additional check

In [8]:
df_customers[df_customers['total_spent'].isnull() & (df_customers['total_orders'] != df_customers['failed_orders'])]

,customer_unique_id,customer_city,customer_state,first_purchase_date,first_purchase_month,last_purchase_date,customer_tenure_days,total_orders,failed_orders,total_spent,avg_order_value
49312,830d5b7aaa3b6f1e9ad63703bec97d23,sao joaquim da barra,SP,2016-09-15 12:16:38,2016-09-01,2016-09-15 12:16:38,0,1,0,NaN,NaN

One anomaly - in original dataset there is one order that doesn't have payment recorded; data quality issue.

In [9]:
df_customers.duplicated().sum()

np.int64(0)

In [10]:
df_monthly_sales.isnull().sum()

purchase_month             0
total_orders               0
total_customers            0
total_revenue              0
avg_order_value            0
avg_orders_per_customer    0
cancelled_orders           0
cancellation_rate          0
unavailable_orders         0
unavailable_rate           0
dtype: int64

In [11]:
df_monthly_sales.duplicated().sum()

np.int64(0)

In [12]:
df_products.isnull().sum()

product_category_name    0
total_orders             0
products_sold            0
total_revenue            0
avg_product_price        0
total_freight            0
avg_freight              0
dtype: int64

In [13]:
df_products.duplicated().sum()

np.int64(0)

In [14]:
df_delivery.isnull().sum()

order_month             0
completed_orders        0
avg_delivery_days       0
median_delivery_days    0
avg_processing_days     0
avg_shipping_days       0
on_time_orders          0
late_orders             0
on_time_rate            0
avg_estimation_error    0
dtype: int64

In [15]:
df_delivery.duplicated().sum()

np.int64(0)

Delivery Summary: We are anticipating null values for orders that don't have order_status 'delivered'; additionaly there should be null values uncovered in SQL part for 'delivered' orders.

In [16]:
df_reviews.isnull().sum()

review_id                 0
order_id                  0
customer_unique_id        0
review_score              0
review_sentiment          0
order_status              0
successful_order          0
purchase_month            0
delivery_days          2865
delivery_delay_days    2865
is_late_delivery       2865
dtype: int64

In [17]:
df_reviews[df_reviews['delivery_days'].isnull() & (df_reviews['order_status'] == 'delivered')]

,review_id,order_id,customer_unique_id,review_score,review_sentiment,order_status,successful_order,purchase_month,delivery_days,delivery_delay_days,is_late_delivery
10679,ee2d30652e2f7fc00861074f795f5bf0,0d3268bad9b086af767785e3f0fc0133,ebf7e0d43a78c81991a4c59c145c75db,5,Positive,delivered,True,2018-07-01,NaN,NaN,None
24366,bb311d9562ecbefc8e4be756d8999892,e69f75a717d64fc5ecdfae42b2e8e086,3bc508d482a402715be4d5cf4020cc81,5,Positive,delivered,True,2018-07-01,NaN,NaN,None
27667,c0dd6bec0375c376f044af102118526f,f5dd62b788049ad9fc0526e3ad11a097,2f17c5b324ad603491521b279a9ff4de,5,Positive,delivered,True,2018-06-01,NaN,NaN,None
52011,4e755f114e50d33b9ac6a56e0d7d3ea9,2d858f451373b04fb5c984a1cc2defaf,d77cf4be2654aa70ef150f8bfec076a6,5,Positive,delivered,True,2017-05-01,NaN,NaN,None
56367,25e11638a3d01a87e8e62338a39eee28,2ebdfc4f15f23b91474edf87475f108e,1bd06a0c0df8b23dacfd3725d2dc0bb9,5,Positive,delivered,True,2018-07-01,NaN,NaN,None
86005,f48c6c944a5d52dcca8ac5c4ec417cf2,2d1e2d5bf4dc7227b3bfebb81328c15f,13467e882eb3a701826435ee4424f2bd,5,Positive,delivered,True,2017-11-01,NaN,NaN,None
88946,d055795a562efffefe47ef81e5435322,20edc82cf5400ce95e1afacc25798b31,175378436e2978be55b8f4316bce4811,5,Positive,delivered,True,2018-06-01,NaN,NaN,None
91979,0d4c56af896dd6eb9de8edbaa1902d22,ab7c89dc1bf4a1ead9d6ec1ec8968a84,cce5e8188bf42ffb3bb5b18ff58f5965,1,Negative,delivered,True,2018-06-01,NaN,NaN,None

Summary: Basic overview, null and duplicate checks in line. Only one unexpected edge case found.