# Introduction

In [2]:
import pandas as pd

In [3]:
pd.options.display.float_format = '{:,.2f}'.format

In [4]:
from src.helpers import load_view
df_customers = load_view("vw_customer_summary_python")

Currently, in the view we have customer_tenure_days defined as days between first and last purchase of customer. While it could potentially be a good metric we are dealing with a dataset where majority of customers ordered only once.

Instead, let's add recency metric, defined as days between last purchase and snapshot date (last date in dataset), for RFM analysis.

In [5]:
analysis_date = df_customers["last_purchase_date"].max() + pd.Timedelta(days=1)

df_customers["recency"] = (
    analysis_date -
    df_customers["last_purchase_date"]
).dt.days

In [6]:
features = [
    "recency",
    "total_orders",
    "total_spent"
]

df_customers[features].describe()

        recency  total_orders  total_spent
count 96,096.00     96,096.00    94,989.00
mean     288.74          1.03       165.69
std      153.41          0.21       226.74
min        1.00          1.00         9.59
25%      164.00          1.00        63.10
50%      269.00          1.00       107.90
75%      398.00          1.00       182.94
max      773.00         17.00    13,664.08

In [8]:
from src.helpers import assign_f_score

df_customers['R_Score'] = pd.qcut(df_customers['recency'], q=5, labels=[5, 4, 3, 2, 1])
df_customers['F_Score'] = df_customers['total_orders'].apply(assign_f_score)
df_customers['M_Score'] = pd.qcut(df_customers['total_spent'], q=5, labels=[1, 2, 3, 4, 5])

In [10]:
df_customers.head()

,customer_unique_id,customer_city,customer_state,first_purchase_date,first_purchase_month,last_purchase_date,customer_tenure_days,total_orders,failed_orders,total_spent,avg_order_value,recency,R_Score,F_Score,M_Score
0,0000366f3b9a7992bf8c76cfdf3221e2,cajamar,SP,2018-05-10 10:56:27,2018-05-01,2018-05-10 10:56:27,0,1,0,141.90,141.90,161,4,1,4
1,0000b849f77a49e4a4ce2b2a4ca5be3f,osasco,SP,2018-05-07 11:11:27,2018-05-01,2018-05-07 11:11:27,0,1,0,27.19,27.19,164,4,1,1
2,0000f46a3911fa3c0805444483337064,sao jose,SC,2017-03-10 21:05:03,2017-03-01,2017-03-10 21:05:03,0,1,0,86.22,86.22,586,1,1,2
3,0000f6ccb0745a6a4b88665a16c9f078,belem,PA,2017-10-12 20:29:41,2017-10-01,2017-10-12 20:29:41,0,1,0,43.62,43.62,370,2,1,1
4,0004aac84e0df4da2b147fca70cf8255,sorocaba,SP,2017-11-14 19:45:42,2017-11-01,2017-11-14 19:45:42,0,1,0,196.89,196.89,337,2,1,4